### ISSUE TITLE
Worth the bandwidth / CPU costs?

### ISSUE THREAD

**Issue by tomByrer** [giltayar/proposal-types-as-comments#100]
People who want to develop JS-target in types can get what right now: Typescript & great IDE support.  There are also other typed transpile-into-JS like [Nim](https://nim-lang.org/features.html) & [V-lang](https://vlang.io/).  If you want to deploy typed JS comments for some reason, there is [JSDoc](https://jsdoc.app/tags-type.html).

Bandwidth scarcity is a real thing, eg throttling cell phone plans after exceeding 4g/5g caps, areas where information is desperately needed but not readily accessible (current events in Eastern Europe, Pacific Rim, etc).   While the extra CPU & memory usage will be small, it [will NOT be zero](https://github.com/giltayar/proposal-types-as-comments/issues/49#issuecomment-1065931759).

Bad enough that JS is taking more & more resources; do we really **need** to encourage extra wasted 'comments'?

**Comment by jeffdesign** [comment]
Yes

**Comment by orta** [comment]
This is largely a duplicate of https://github.com/giltayar/proposal-types-as-comments/issues/35 - any of the feedback in there applies here, if you would minimize your code for deployment then that same process would strip types.

**Comment by tomByrer** [comment]
> largely a duplicate of #35

Thanks, moving to that thread.
