### ISSUE TITLE
WebAssembly compatibility: Int64 instead of number (Like AssemblyScript)

### ISSUE THREAD

**Issue by MichaelPeter** [giltayar/proposal-types-as-comments#101]
Typescript was concived before WebAssembly, so there is just a number type instead of Int32, Int64, Float etc.

Instead of defining just the comment number, couldn't we also not additionally also define more specific numeric values like
Int64, Float64 etc?

If we would also introduce Int64, the typescript/javascript code could also be used to not only compile javascript, but also to compile more directly to WebAssembly.

**Comment by orta** [comment]
Doing so would require specing out a type-system and getting consensus on that. Which isn't a goal for this proposal - you might want to ask upstream in the TypeScript repo, but a type system which _does_ take these specific types values could be built in the syntax space from this proposal.

**Comment by benjamingr** [comment]
Going to go ahead and close as out of scope (agree with orta) since it's about the type system itself.

I think this sort of idea/change is enabled by this proposal rather than it preventing it.

**Comment by MichaelPeter** [comment]
thank you for the reply
