### ISSUE TITLE
Explicitly state that JSX is also used in SolidJS ecosystem?

### ISSUE THREAD

**Issue by trivikr** [giltayar/proposal-types-as-comments#102]
JSX is omitted from this proposal, and it's called out that it's widely used in [the React Ecosystem](https://reactjs.org/docs/introducing-jsx.html) for follow-up in other proposals. 
https://github.com/giltayar/proposal-types-as-comments/#omitted-jsx

The JSX is also used in [the SolidJS ecosystem](https://www.solidjs.com/tutorial/introduction_jsx), which is popular primarily because of it's fine-grained reactivity and performance.

Should we add link to SolidJS ecosystem too?

**Comment by tomByrer** [comment]
There are a few more JSX-ish FE libraries.  SolidJS is one of the more popular ones, though I think Preact has more installs.

**Comment by orta** [comment]
I don't think we need to be more explicit for the different use cases of JSX, we already call out that it is used in different libs/frameworks and there's no extra value to the spec in mentioning some of the smaller players given the size of the react ecosystem vs the others.

From the README today:

> [JSX](https://facebook.github.io/jsx/) is an XML-like syntax extension to JavaScript that is designed to be transformed by a pre-processor into valid JavaScript. It is widely used in [the React ecosystem](https://reactjs.org/docs/introducing-jsx.html), but it has been used for different libraries and frameworks.

**Comment by benjamingr** [comment]
I personally use solid in my own projects but there is no denying SolidJS is (currently) a lot smaller of an ecosystem than React.

As mentioned before there are a bunch of those not just Solid and React
