### ISSUE TITLE
Carving out a place for type-annotations is going to be really difficult

### ISSUE THREAD

**Issue by theScottyJam** [giltayar/proposal-types-as-comments#105]
Right now, the README is a bit hand-wavy about how type annotations will work, basically saying "we'll figure it out, using bracket matching and what-not", but I'm honestly not sure how easy this is to do. Let's consider a handful of places where type annotations would be allowed:

```typescript
let x: typeAnnotation
const y: typeAnnotation = 2
const fn = (x: typeAnnotation, y: typeAnnotation = 0): typeAnnotation => ...
function fn(x: typeAnnotation): typeAnnotation { ... }
return x as typeAnnotation
```

How do we know when a type annotation ends?
* In an assignment, the `=` could terminate the type annotation.
* In a function declaration, `=>`, `,`, `=`, or `{` could terminate it.
* The type annotation might also appear right in the middle of an expression, because of the `as` operator, making it really difficult to know where it ends (i.e. in `x as a | b`, is that `|` a bitwise or, or a union type operator?)
* In the declaration without an assignment, if a semicolon is missing, the type-annotation will end when... a syntax error happens and ASI kicks in and forces a semicolon somewhere? That wouldn't work well, it could accidentally consume a lot of extra code on the next line. Alternatively, we could make it sensitive to new lines? But, that gets awkward if you want to make your type annotation span multiple lines, e.g. I could imagine someone writing code like this:
  ```typescript
  let x: { a: whatever, b: whatever, c: whatever }
         | { a: whatever, d: whatever } 
  ```

Of course, if things get too complicated, you can always force the end-user to put parentheses around the type annotation, but ideally, we would have consistent rules about when parentheses are required. It would be annoying if you can do `a | b` in some locations without parentheses but other locations require it.

Also, in a function declaration, the fact that a `{` character can terminate the type annotation could be a real pain point, considering we like using the `{` character in types as well.

I'd like to open a discussion on how we could resolve these issues, because, I'm not convinced this is really possible, and I think it's very possible that most type annotations will have to be wrapped in parantheses if we want to have consistent rules. i.e. we're going to have a lot of this going on:

```typescript
function doThing(arg1: (number | undefined), arg2: (readonly number[]), arg3: ((x: int) => void)): void { ... }
```

**Comment by acutmore** [comment]
> Right now, the README is a bit hand-wavy about how type annotations will work, basically saying "we'll figure it out, using bracket matching and what-not",

Hi @theScottyJam!

Have you checked out the [tentative grammar](https://giltayar.github.io/proposal-types-as-comments/grammar.html)? There is a link to it in the README but it’s easy to miss.

This, while subject to change, provides the concrete details on how to determine where type comments start and end.

**Comment by theScottyJam** [comment]
Oh, interesting. The type annotations are a lot more rigid than I thought they would be. Inside parentheses and what-not you're free to do what you want, but outside, it's very specific to TypeScript's current syntax. I got the impression from the README that they were going to avoid being that rigid with the syntax.

Ok, well I guess this answers my question, so I'll close this.

**Comment by giltayar** [comment]
@theScottyJam @acutmore please treat the tentative grammar as kind of a "let's see if we can do something" and not a concrete proposal. To reach stage 1, we don't necessarily need to define what that grammar is, but reach an agreement that the ideas of "types as comments" are worth pursuing. 

I, for one, would love to pursue them!
