### ISSUE TITLE
Why types should be part of js?

### ISSUE THREAD

**Issue by ksevelyar** [giltayar/proposal-types-as-comments#109]
Typescript is cargo cult of the system programming world which reduces maintainability. Correct strong types in browser is Rust code compiled to wasm.

* mythical stability (only auto tests can provide some stability)
* reduces readability (=== maintainability)
* 0 runtime optimizations

**Comment by theScottyJam** [comment]
@ksevelyar - this thread isn't going to be productive if you start by saying the community in favor of this proposal is just part of a "cargo cult", then give some huge claims without any attempt to back it up.

If you want to try and have an open conversation about whether or not types are an appropriate thing for JavaScript, that can certainly be done here, but for it to be of any value, both parties of the conversation need to be able to have an open mind and be willing to try and understand where the other is coming from. But, from the way this thread got started (calling everyone else part of a cargo cult), I'm worried that sort of thing is not going to happen here, and if this thread was actually persued, we'd all just end up mad at each other and none-the-wiser.

**Comment by benjamingr** [comment]
I'm going to go ahead and close this. I find this sort of comments making strawman arguments as if they're factual without reading the README (that indicates that this proposal actually _enables_ the sort of type system you suggest if people want to write a checker) very aggressive and this violates the code of conduct.

Please refrain from this sot of comment calling the user of any language "cargo cult programmers".

**Comment by ksevelyar** [comment]
Yes and it will increase fragmentation of js. Which already most fragmented lang. 

Sorry, I think Typescript is shitty product.

**Comment by ksevelyar** [comment]
I believe types increases fragmentation of js ecosystem without any benefits. Typescript is an example of doing this with external library.
