### ISSUE TITLE
Effect on file size

### ISSUE THREAD

**Issue by alshdavid** [giltayar/proposal-types-as-comments#111]
Type annotations increase file size and with JavaScript being a compile target for the vast of web developers, type annotations would either be unused or contribute to larger file sizes.

Outside of runtime access to `type` and `interface`s, If we are all using compilers anyway, what's the use of adding this to the language?

Further, what's the advantage of this proposal over focusing on refining web assembly such that it can serve as a compile target for TypeScript?

**Comment by noelmace** [comment]
@alshdavid I believe (some of) your questions may be a duplicate #35

**Comment by orta** [comment]
Agree, closing as duplicate
