### ISSUE TITLE
How does this proposal compare to Flow comment types

### ISSUE THREAD

**Issue by claudepache** [giltayar/proposal-types-as-comments#115]
The explainer says:

> Here's an example of the JSDoc-based type syntax from [TypeScript's JSDoc Reference](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#param-and-returns).
> 
> ```js
> /**
>  * @param {string}  p1 - A string param.
>  * @param {string=} p2 - An optional param (Closure syntax)
>  * @param {string} [p3] - Another optional param (JSDoc syntax).
>  * @param {string} [p4="test"] - An optional param with a default value
>  * @return {string} This is the result
>  */
> function stringsStringStrings(p1, p2, p3, p4="test") {
>     // TODO
> }
> ```
> And here's the equivalent TypeScript syntax enabled by this proposal.
> 
> ```js
> function stringsStringStrings(p1: string, p2?: string, p3?: string, p4: string = "test"): string {
>     // TODO
> }
> ```

Of course, JSDoc is not just about declaring, it is also about documenting. So, this is really comparing oranges to apples.

If you are fair, you should compare the proposed syntax with [Flow comment types](https://flow.org/en/docs/types/comments/): 

```js
function stringsStringStrings(p1 /*: string */, p2 /*: ?string */, p3 /*: ?string */, p4 /*: string */ = "test") /*: string */ {
    // TODO
}
```

The result of the comparison can and should be debated. But types in comments are certainly not, as the FAQ item “[Why not stick to existing JS comment syntax?](https://github.com/giltayar/proposal-types-as-comments#why-not-stick-to-existing-js-comment-syntax)” is suggesting, “*much* more verbose and unergonomic”.

**Comment by bakkot** [comment]
See also https://github.com/giltayar/proposal-types-as-comments/issues/41

**Comment by DanielRosenwasser** [comment]
I think you can argue that the inline comments at every point tend to be somewhat moe verbose as well; however, we should continue that discussion at #41.
