### ISSUE TITLE
Should be considered: Runtime type assertion

### ISSUE THREAD

**Issue by adrianhelvik** [giltayar/proposal-types-as-comments#117]
I was anticipating a good types proposal, despite not being a very big TypeScript/Flow user, it would be nice to be able to have type assertions to help me secure critical paths. This proposal would positively remove the possibility for such a proposal. Are we certain that this would not be useful?

I definitely understand why the proposal exists – type checking in your editor and real live code in the browser. But with newer, faster tools like Vite this is hardly a real problem anymore.

Additionally, it feels very very wrong to me to have actual code with incorrect no-op type assertions.

So, I am very apprehensive about this. And I do not believe it should be rushed.

What are your thoughts on this? What is the pressing need that would make the language better?

**Comment by giltayar** [comment]
> This proposal would positively remove the possibility for such a proposal. Are we certain that this would not be useful?

See the FAQ entry https://github.com/giltayar/proposal-types-as-comments#how-could-runtime-checked-types-be-added-in-future

**Comment by adrianhelvik** [comment]
Ah, I'm not thinking about performance improvement. I'm thinking about runtime type assertions.

**Comment by giltayar** [comment]
> Ah, I'm not thinking about performance improvement. I'm thinking about runtime type assertions.

So is the faq entry I linked to.

**Comment by DanielRosenwasser** [comment]
I think the FAQ entry answers this. There's also room for a `"use typechecks"` directive that could layer on top of the proposal. But there's going to be no rush about this. This proposal has to go through committee review, gather feedback, and go through a staging process for what might take years.
