### ISSUE TITLE
Wondering where type checker is

### ISSUE THREAD

**Issue by KSH-code** [giltayar/proposal-types-as-comments#123]
> allowing those annotations to be checked by a type checker that is external to JavaScript.

To me, It means like type checked by external tools.
it may be IDE? what is the meaning exactly?

can it be checking type while writing code?

> At runtime, a JavaScript engine ignores them, treating the types as comments.

It can be divided environment?

when I develop, I'd like to know error where it is.

by the way, it is in production, it cannot be raised an error.

**Comment by orta** [comment]
Yep, the errors could come from your IDE or it could be a CLI tool you run ahead of time. As JavaScript ignores the types, then it would not raise errors if the types don't work in the type system you use.

**Comment by KSH-code** [comment]
> Yep, the errors could come from your IDE or it could be a CLI tool you run ahead of time. As JavaScript ignores the types, then it would not raise errors if the types don't work in the type system you use.

Thank you for the reply.
one more question is that can I detect a type error in development at runtime?

**Comment by orta** [comment]
I guess it depends on what you mean by runtime. 

The types are ignored by the JavaScript runtime, so you can't check for them in the JS runtime. But, if you mean showing your type errors inside a bundlers etc, then yeah people are already doing that today - so I'd assume they will be doing that in JS + types as comments.

**Comment by KSH-code** [comment]
Aha I got it.
I was thinking if a type error is detected at runtime in only development is awesome.
My question is solved thx!
