### ISSUE TITLE
Explicit conditions for removal from the spec

### ISSUE THREAD

**Issue by fabiospampinato** [giltayar/proposal-types-as-comments#68]
I'm pretty worried that this proposal will lead us the wrong way and constrain our future choices in ways that we don't currently fully understand. 

Plus it's a big change to the language that doesn't actually do anything useful at runtime.

I'd personally be more in favor of trying something like this if there was a clear an agreed upon path for removing it from the spec in case a series of conditions were met, like for example maybe if less than 0.1% of websites use it 10 years from now then we can cleanup the spec.

I understand that proposals aren't usually approved with a sunset clause, but approving something like this without a way to get rid of it if it turns out to be a bad choice seems really risky to me.

**Comment by ljharb** [comment]
No such clause has any meaning; we won’t break the web, so if it ships, it’s permanent.

**Comment by fabiospampinato** [comment]
It doesn't work like that though, they removed `alert` from iframes for example I believe.

**Comment by ljharb** [comment]
@fabiospampinato _we_, meaning, TC39. `alert` isn't part of any specification TC39 governs.

That it is technically possible to remove something doesn't mean it would ever be practical; i would happily bet hard cash that if this ships, it will be a permanent irrevocable part of the web within a year, let alone 10.

**Comment by theScottyJam** [comment]
If it ships with a "sunset clause", I wouldn't want to start using it for fear that my code might stop working one day. I'd only start using it once it's been decided to be a permanent addition to the EcmaScript.

If many people are like me in this regard, it makes it much harder to create a "sunset clause", because it's hard to know how many people are waiting to use it until this trial period is over.

**Comment by matthew-dean** [comment]
@fabiospampinato Yeah, this is something that's bothering me as well, despite me being a fan of TypeScript. Accepting this would almost 100% guarantee there could never be an explicit type system in JavaScript.

The argument that there can't be is, IMO, completely ridiculous:

> Additionally, defining a type system to run directly in the browser means that improved type analyses would become breaking changes for the users of JavaScript applications, rather than for developers. This would [violate goals around web compatibility (i.e. "don't break the web")](https://github.com/tc39/how-we-work/blob/cc47a79340a773876cb03371dc2d46b9d9ce9695/terminology.md#web-compatibilitydont-break-the-web), so type system innovation would become near-impossible.

This is just a silly statement and lacks imagination. There are definitely more explicit type systems that could be non-breaking.

IMO the best / most promising part of the proposal is: 
```
class Point {
  %public %readonly x: number

  @@public @@readonly x: number
}
```
e.g. just limiting this spec to a kind of concise 3rd comment syntax.

**Comment by fabiospampinato** [comment]
> That it is technically possible to remove something doesn't mean it would ever be practical; 

I'm not sure how practical it would be matters much, the most important part as far as I'm concerned is that it's possible and there's no scenario where we are stuck with something that potentially makes the language significantly worse (by hindering other proposals perhaps) forever.

> i would happily bet hard cash that if this ships, it will be a permanent irrevocable part of the web within a year, let alone 10.

I mean I think it's certain that if this is accepted it won't be deleted right away, we would need to wait a while to be able to understand with good probability if it was worth it or not.

> If it ships with a "sunset clause", I wouldn't want to start using it for fear that my code might stop working one day. I'd only start using it once it's been decided to be a permanent addition to the EcmaScript.

Good point, but it depends on the threshold I think. Like if we are talking about 0.1% utilization would you still not use it for fear that it will get deleted? And if you have this fear with a 0.1% utilization threshold why start using it in the first place, we can only get to that percentage if this turns out almost entirely useless in the eyes of the community, if it's not useless to you you already made your bet.

**Comment by ljharb** [comment]
I think you're misunderstanding how "don't break the web works" - it's not an objective or clear rubric. It's possible that a single sufficiently popular website breaking when a feature is removed would guarantee the feature could never be removed.

**Comment by theScottyJam** [comment]
There's other ways to gage how likely people are to use a feature before we put it out in the wild. For example, we can conduct polls, or ask big companies if they would use it, or just get a general sentiment of the excitement around this feature. The fact that static typing is the number one requested JavaScript feature (according to the README) shows that a large portion of the community would like something along these lines (though, it's possible they had something different in mind when they answered that poll).

**Comment by fabiospampinato** [comment]
> I think you're misunderstanding how "don't break the web works" - it's not an objective or clear rubric. It's possible that a single sufficiently popular website breaking when a feature is removed would guarantee the feature could never be removed.

I didn't mean to imply that we must use the 0.1% threshold I mentioned kind of randomly, personally I'd be happy with _any_ set of conditions the committee would be happy with, hypothetically. Just acknowledging this possibility and preparing _somewhat_ for it should be good enough.

**Comment by ljharb** [comment]
The preparation is already part of the process - advancing it to stage 3 means the committee is endorsing shipping it, and is willing for it to become a permanent part of the language. All features retain the remote possibility of removal at any time, and all of them face the likely reality of never being removable once shipped - this one would be no different.

**Comment by fabiospampinato** [comment]
Fair enough.
