### ISSUE TITLE
Explicitly make "runtime performance improvements" a non-goal

### ISSUE THREAD

**Issue by mathiasbynens** [giltayar/proposal-types-as-comments#75]
There were a few comments suggesting that JS engines should somehow make use of the typing info to improve runtime performance. (FWIW, I tried to clear some of this up here: https://twitter.com/mathias/status/1501934337062670354)

I think it would be useful to explicitly make it clear that this is a non-goal for this proposal, perhaps in the FAQ.

**Comment by DanielRosenwasser** [comment]
I guess I can at least here say that we don't believe runtime performance is a goal of this proposal, nor do we think it has much impactful potential for engines. Maybe we can put it in the FAQ.

**Comment by simonbuchan** [comment]
Given the theoretical use of them *for* runtime performance improvements (e.g. a (new or existing!) runtime that has a fast-path for specific type hints), I wouldn't be too strong on the non-goal statement?

**Comment by ljharb** [comment]
Unless implementers explicitly indicate it’s something they’d pursue, or that it’d actually lead to performance improvements (it’s very unclear that it would, in fact), it seems safest to assume that it’s more than just a non-goal - that it will *not* lead to any perf improvements.

**Comment by simonbuchan** [comment]
*More* than just a non-goal? That would imply that you would go out of your way to ensuring it *couldn't* be used for performance reasons!

I'm only saying that some non-goal statement would be more like "don't expect performance improvements" not "could not be used for performance improvements".

Not an expert, but from my middling understanding of V8's internals, I don't see anything obviously blocking having things like shapes, SMI and the like being the declared types, and letting the JIT run early to skip the interpreter / feedback path? Cases like ASM.js show it's hardly that easy, but at least it seems plausible and valuable enough that with this proposal in place I'd be surprised if no-one tried something.

**Comment by ljharb** [comment]
@simonbuchan lol fair, what i meant was, that a non-goal is something that you aren't optimizing for. I'm saying that it's also *not going to happen*.

**Comment by simonbuchan** [comment]
@ljharb graveyards are littered with attempts to annotate JavaScript for performance, which means both that it's really really hard, and that people really really want it!

I guess I just feel that this proposal adds a lot of grease to a previously gritty area of the problem, so I'm at least a bit more optimistic.

Perhaps it's more "you won't be *writing* annotations for improving performance"?

**Comment by simonbuchan** [comment]
In any case, I only think the "would not allow" in the above PR is a bit strong due to English screwery, I think it's aiming for "does not make possible"? The proposed edit by @robpalme is above and beyond.

**Comment by mathiasbynens** [comment]
Closing this now that #86 has been merged. Nice work, everyone!
