### ISSUE TITLE
How about this term? type hints

### ISSUE THREAD

**Issue by bl0cknumber** [giltayar/proposal-types-as-comments#79]
Some people avoid the term of types as a comment, and they suggest type annotations or rather _unchecked type annotations_ but I think the use of the word **type hints** is much more reasonable.

Ref: https://docs.python.org/3/library/typing.html

“There are only two hard things in Computer Science: cache invalidation and naming things.”
— Phil Karlton

**Comment by bl0cknumber** [comment]
Also, we can start planning to pull off standard additional third parties to get pulled out of all the advantages using the type system.

**Comment by bl0cknumber** [comment]
![YKW ICT A H](https://media.giphy.com/media/l4Ep1BUyOcG6O5SCY/giphy.gif)

**Comment by bakkot** [comment]
"hints" implies it's a hint to the engine, which it definitely will not be: https://github.com/giltayar/proposal-types-as-comments/issues/75

**Comment by wparad** [comment]
> "hints" implies it's a hint to the engine, which it definitely will not be: #75

to you maybe, but a hint is just a hint, we can call it `type hints for IDEs and build tools` is that better?

**Comment by bl0cknumber** [comment]
> "hints" implies it's a hint to the engine, which it definitely will not be: #75

You can imply the hint to the third parties, not just an engine.

As you can read at the part of the reference link above:
`They can be used by third-party tools such as type checkers, IDEs, linters, etc.`

**Comment by orta** [comment]
This thread seems to largely be a duplicate of https://github.com/giltayar/proposal-types-as-comments/issues/78
