### ISSUE TITLE
Have an explicit stance on reflection

### ISSUE THREAD

**Issue by jimisaacs** [giltayar/proposal-types-as-comments#89]
This issue is based on a general concern regarding the current (while this issue is being filed) section on reflection. It could be more explicit and direct:

> Can types be available via runtime reflection like [TypeScript's emitDecoratorMetadata](https://www.typescriptlang.org/tsconfig#emitDecoratorMetadata)?
>
> The proposal here differs significantly from Python's types, as the types in this proposal are entirely ignored, not evaluated as expressions or accessible at runtime as metadata. This difference is largely motivated by the existing community precedent, where JS type systems do not tend to use JS expression grammar for their types, so it is not possible to evaluate them as such.
>
> At most, we could expose the types as strings, but it's not clear what anyone could do with those or how they should be exposed. This proposal does not try and expose the types as metadata, and only specifies that they are ignored by the JS runtime. Users who rely on decorator metadata could continue to leverage a build step as desired.

I think a more solid stance needs to be addressed here. Though my thoughts are still not concrete, here they are...

My general stance is against the use of reflection outside of developer tooling, so if it's something that could be enabled in a debug or maybe "dev" mode, it would be ok. Outside of that, without being more explicit in the proposal, maybe a compiler takes their own direction and may decide to include it, without a developer centric barrier, and maybe it exposes too much introspection possibilities to the web, which in turn opens up a whole new, and _unnecessary_, direction in meta programming. So either maybe say this proposal proposes not to include reflection at runtime, or it proposes to include it in this explicit mode, flag, context, etc..

**Comment by giltayar** [comment]
As the FAQ said, the JS community has spoken: types are not currently used as metadata in TypeScript or Flow, and there hasn't been much requests for this. I _have_ seen somebody happy that the `function.toString()` will include the types and thus be amenable to some metaprogramming, but I believe this will be mostly a curiosity, and not something that can be of heavy use, because they won't be able to access other parts of the types (e.g. `interfaces`-es).

**Comment by benjamingr** [comment]
I'm not sure the proposal should have a stance on this vs. leaving this for future proposals. The main reason is that this proposal does not block further work in this space but rather enables it.

**Comment by jimisaacs** [comment]
@benjamingr good point, will think more on it

**Comment by jimisaacs** [comment]
You know @benjamingr i like that point so much, maybe that is what needs to basically go in there. i.e. "the reason this stance is not explicit is because of...".

**Comment by benjamingr** [comment]
@giltayar wdyt? Happy to make a PR to add this to the README

**Comment by giltayar** [comment]
@benjamingr 👍

**Comment by benjamingr** [comment]
Sure https://github.com/giltayar/proposal-types-as-comments/pull/94 @giltayar
