### ISSUE TITLE
Beside `Array<A>`, also allowing using function application syntax -- `Array(A)`, to application a (generic) type to its arguments, for adding dependent types to JavaScript in the future.

### ISSUE THREAD

**Issue by xieyuheng** [giltayar/proposal-types-as-comments#92]
For example, if `Equal(Nat, add(x, y), add(y, x))` is a valid "types-as-comments",
we will be able to express "the commutative property of addition for natural number"
like the following type:

```js
function add_commute(
  x: Nat, y: Nat,
): Equal(Nat, add(x, y), add(y, x)) {
  ...
}
```

Which reads as

> For all `x` and `y` of `Nat` (natural number),
> we have `x + y = y + x`.

More examples at: https://readonly.link/manuals/cicada-lang/cicada

**Comment by xieyuheng** [comment]
For example, if `Equal(Nat, add(x, y), add(y, x))` is a valid "types-as-comments",
we will be able to express "the commutative property of addition for natural number"
like the following type:

```js
function add_commute(
  x: Nat, y: Nat,
): Equal(Nat, add(x, y), add(y, x)) {
  ...
}
```

**Comment by giltayar** [comment]
@xieyuheng we do not define what is in the "type space" allocated for types. So this proposal as it currently stands, would allow `Array<A>`, `Array(A)`, and even `Array{[(!A!)]}`.

**Comment by xieyuheng** [comment]
Great!
