### ISSUE TITLE
Do we have plan to prototype a parser to collect feedback with runnable examples?

### ISSUE THREAD

**Issue by xieyuheng** [giltayar/proposal-types-as-comments#96]

**Comment by benjamingr** [comment]
This was considered earlier (or just a babel transform) though this is just a limited subset of TypeScript/babel's transpile transform so it appears there is already a tremendous amount of feedback on the syntax/usage

**Comment by ljharb** [comment]
Either way, stage 0 is far too premature for that; that’s something that would generally wait until stage 2, due to the very high likelihood of syntax change.

**Comment by xieyuheng** [comment]
Thanks for the replies.
