### ISSUE TITLE
Types aren't comments, like class constructor public/private

### ISSUE THREAD

**Issue by kungfooman** [giltayar/proposal-types-as-comments#98]
TS:

```ts
class Point {
  constructor(public x = 0, public y = 0, public z = 0) {
    // nothing yet
  }
}
```

Using TS Playground, it transpiles into:

```js
"use strict";
class Point {
    constructor(x = 0, y = 0, z = 0) {
        this.x = x;
        this.y = y;
        this.z = z;
        // nothing yet
    }
}
```

TLDR: Don't refer to TypeScript all the time when this is breaking TypeScript code.

**Comment by acutmore** [comment]
Hi @kungfooman 

Parameter properties not being part of this proposal is explicitly mentioned in the README here:

https://github.com/giltayar/proposal-types-as-comments#omitted-typescript-specific-features-that-generate-code

**Comment by benjamingr** [comment]
Yes as mentioned this is already addressed in the README.
