### ISSUE TITLE
Limit: types and typescript are evolving very frequently

### ISSUE THREAD

**Issue by lifaon74** [giltayar/proposal-types-as-comments#99]
Even if I love and use only typescript I strongly doubt that an official tc39 proposal could ever exists for a simple reason: types are pretty new and still evolving a lot.

Let me clarify:

Typescript's types are still suffering from many limits (named templates, recursive types, superset in unions, etc...). We can see it especially with its [5k+ issues](https://github.com/microsoft/TypeScript/issues). Don't get me wrong, typescript is great, but you have to understand that it's still evolving.

We see new improvements, types and modifiers at each releases, meaning it's still far from perfection even if it covers 99% of usecases. Moreover some typescript improvements **are breaking changes FOR a very good reason** (ex: strictNullCheck, some tuples generations or variadic length, Tail-Recursion Elimination, etc...). There breaking changes are highly required by the community, and mostly necessary. However, tc39 doesn't admit breaking changes, for a good and essential reason: don't break the web.

So this strongly conflict between:

- being able to fast update the types, with breaking changes (typescript / this proposal)
- and something far more stable, with highly designed and documented specs (tc39 proposals)

On my point of view, these are not reconcilable:

- typescript does a perfect job on it's side
- just like the tc39, but with different constraints and requirements

**Comment by acutmore** [comment]
Hi @lifaon74 - this proposal does not put constraints on the underlying type system itself. e.g `stictNullChecks`.

The proposal is more about making an official syntactic space available for projects like TypeScript/Flow/Hegel/etc.

Having an official space for syntax _could_ allow these projects to move faster without worry of conflicting with other EcmaScript proposals.

**Comment by benjamingr** [comment]
Yeah, as @acutmore explained you make a very good point and it is in fact so good that a considerable amount of the design here is about _not_ preventing evolution in the type system by making the concern (type checking) explicitly external (at least initially).
